### ISSUE TITLE
Custom yaml package

### ISSUE THREAD

**Issue by tartavull** [cachix/pre-commit-hooks.nix#172]
Thank you for making `pre-commit-hooks.nix`!

My ` .pre-commit-config.yaml` looks like:

```
exclude: (^proto/)|(vendor/)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-xml
      - id: check-json
        exclude: ^(.+\/)*(\.vscode|\.devcontainer)\/.*$
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: debug-statements
      - id: requirements-txt-fixer
  - repo: https://github.com/prettier/pre-commit
    rev: v2.1.2
    hooks:
      - id: prettier

  - repo: https://github.com/yoheimuta/protolint
    rev: v0.32.0
    hooks:
      - id: protolint
        args:
          - "-fix"
```

It seems that `prettier` is available but not the other two repos. How should I go about adding them?
