### ISSUE TITLE
Feature request: hooks for mypy, pyupgrade and flynt

### ISSUE THREAD

**Issue by arjan-s** [cachix/pre-commit-hooks.nix#238]
Examples from my current `.pre-commit-config.yaml`:
```
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
        exclude: /migrations/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        additional_dependencies: ['types-requests', 'types-python-dateutil', 'types-pytz']
        exclude: /migrations/
  - repo: https://github.com/ikamensh/flynt/
    rev: '0.77'
    hooks:
      - id: flynt
        exclude: /migrations/
```
